import { NgModule } from '@angular/core';

import { DynamicFormFieldComponent } from './dynamic-form-field.component';
import {
    ArrayFieldModule,
    ContezzaAutocompleteFieldModule,
    ContezzaButtonToggleFieldModule,
    ContezzaCheckboxFieldModule,
    ContezzaChipsInputFieldModule,
    ContezzaDateFieldModule,
    ContezzaDateRangeChipFieldModule,
    ContezzaDateRangeFieldModule,
    ContezzaDateRangeSingleFieldModule,
    ContezzaDateTimeFieldModule,
    ContezzaDynamicFieldModule,
    ContezzaInfoFieldModule,
    ContezzaInputDialogFieldModule,
    ContezzaInputFieldModule,
    ContezzaMultiautocompleteFieldModule,
    ContezzaPeopleGroupPickerFieldModule,
    ContezzaRadioButtonFieldModule,
    ContezzaSelectFieldModule,
    ContezzaSubformFieldModule,
    ContezzaTextareaFieldModule,
    ContezzaToggleFieldModule,
    HelpFieldModule,
} from '../form-fields';

@NgModule({
    imports: [
        ArrayFieldModule,
        ContezzaAutocompleteFieldModule,
        ContezzaButtonToggleFieldModule,
        ContezzaCheckboxFieldModule,
        ContezzaChipsInputFieldModule,
        ContezzaDateFieldModule,
        ContezzaDateRangeSingleFieldModule,
        ContezzaDateRangeFieldModule,
        ContezzaDateRangeChipFieldModule,
        ContezzaDateTimeFieldModule,
        ContezzaDynamicFieldModule,
        ContezzaInfoFieldModule,
        ContezzaInputFieldModule,
        ContezzaInputDialogFieldModule,
        ContezzaMultiautocompleteFieldModule,
        ContezzaRadioButtonFieldModule,
        ContezzaSelectFieldModule,
        ContezzaSubformFieldModule,
        ContezzaTextareaFieldModule,
        ContezzaToggleFieldModule,
        ContezzaPeopleGroupPickerFieldModule,
        DynamicFormFieldComponent,
        HelpFieldModule,
    ],
    exports: [DynamicFormFieldComponent],
})
export class ContezzaDynamicFormFieldModule {}
