# ----------------------------------
# Contezza Apps Community
# ----------------------------------

stages:
    - build-publish

variables:
    MAVEN_CLI_OPTS: '-s .m2/settings.xml --batch-mode'
    MAVEN_OPTS: '-Dmaven.repo.local=/data/gitlabrunner-cicd/.m2/repository'

#----------------------------
# BUILD + PUBLISH LIBS
#----------------------------

build_publish:
    stage: build-publish
    image: harbor.contezza.nl/tooling/docker-npm-maven:1.0.7
    script:
        - git config --global advice.detachedHead false
        - npm config set @contezza:registry https://nexus.contezza.nl/repository/npm-releases/
        - npm config set //nexus.contezza.nl/repository/npm-releases/:_authToken ${NPM_TOKEN}
        - npm config set legacy-peer-deps true
        - npm i -g nx && npm ci
        - chmod -R 777 ./
        - npm run publish-libs ${CI_NPM_STAGE}
    only:
        variables:
            - $CI_COMMIT_MESSAGE =~ /build-publish/
    tags:
        - cntz-cicd
