== Release notities

Overzicht van de release notities.

=== Overzicht


[cols="20,10,70"]
.Overzicht releases
|===
|Datum |Versie  |Omschrijving

|2023-10-12
|2.3.0
|Bekijk de <<Release 2.3.0,release details>>.

|2023-09-26
|2.2.3
|Bekijk de <<Release 2.2.3,release details>>.

|2023-09-18
|2.2.2
|Bekijk de <<Release 2.2.2,release details>>.

|2023-09-14
|2.2.1
|Bekijk de <<Release 2.2.1,release details>>.

|2023-09-04
|2.2.0
|Bekijk de <<Release 2.2.0,release details>>.

|2023-08-16
|2.1.0
|Bekijk de <<Release 2.1.0,release details>>.

|2023-07-20
|2.0.2
|Bekijk de <<Release 2.0.2,release details>>.

|2023-07-11
|2.0.1
|Bekijk de <<Release 2.0.1,release details>>.

|2023-07-04
|2.0.0
|Bekijk de <<Release 2.0.0,release details>>.

|2023-06-14
|1.1.0
|Bekijk de <<Release 1.1.0,release details>>.

|2023-05-23
|1.0.8
|Bekijk de <<Release 1.0.8,release details>>.

|2023-05-12
|1.0.7
|Bekijk de <<Release 1.0.7,release details>>.

|2023-05-05
|1.0.6
|Bekijk de <<Release 1.0.6,release details>>.

|2023-04-18
|1.0.5
|Bekijk de <<Release 1.0.5,release details>>.

|2023-04-07
|1.0.4
|Bekijk de <<Release 1.0.4,release details>>.

|2023-04-06
|1.0.3
|Bekijk de <<Release 1.0.3,release details>>.

|2023-03-29
|1.0.2
|Bekijk de <<Release 1.0.2,release details>>.

|2023-03-20
|1.0.1
|Bekijk de <<Release 1.0.1,release details>>.

|2023-03-17
|1.0.0
|Bekijk de <<Release 1.0.0,release details>>.

|===

=== Release details

In onderstaande paragrafen worden de release details beschreven.

:sectnums!:

==== Release 2.3.0

Bugfixes/minor changes:

- @contezza/core/context - `ActionsService` filtert en sorteert alle actions onafhankelijk van hun bron.
- @contezza/core/utils - `Jwt` class aangemaakt. `ContezzaJwtUtils` hernoemd naar `JwtUtils`.
- @contezza/dynamic-forms - Velden `checkbox` en `toggle` ondersteunen `settings.color`.

==== Release 2.2.3

Bugfixes/minor changes:

- @contezza/core/pipes - `displayWith`, `getValue` en `includes` aangemaakt.
- @contezza/dynamic-forms - Veld `multiautocomplete` ondersteunt `settings.showSelectAllOption` en accepteert spaties in zijn input veld https://support.contezza.nl/issues/25663[[#25663]].


==== Release 2.2.2

Bugfixes/minor changes:

- @contezza/dynamic-forms - Veld `input` stelt `min` en `max` in gebaseerd op validators.

==== Release 2.2.1

Bugfixes/minor changes:

- @contezza/core/dialogs - `DialogLoaderService` aangemaakt.
- @contezza/core/utils - `ContezzaArrayUtils.sortBy` ondersteunt een extra parameter `options?: { ascending?: boolean }`.
- @contezza/core/utils - `ContezzaArrayUtils.pluck` aangemaakt.
- @contezza/core/utils - `ObjectUtils.getValue` aangemaakt.
- @contezza/core/utils - `ObjectUtils.resolveImports` en `ObjectUtils.replace` verwijderd.
- @contezza/core/utils - Type `KeyOf` herwerkt.
- @contezza/core/utils - Type `TypeOf` aangemaakt.
- @contezza/common - i18n uitbreiden.
- @contezza/dynamic-forms - `ContezzaDynamicFormService.get` en `ContezzaDynamicSearchFormService.get` ondersteunen input van type ExtendedDynamicFormId
- @contezza/dynamic-forms - Veld `help` aangemaakt.
- @contezza/dynamic-forms - Veld `multiautocomplete` toont als het `required` is.

==== Release 2.2.0

Bugfixes/minor changes:

- @contezza/core/dialogs - `DialogTitleComponent` en bijbehorende models aangemaakt
- @contezza/core/popover - Nieuwe library aangemaakt
- @contezza/core/utils - Parameter `evaluator` in `ContezzaAdfUtils.makeRules` ondersteunt `args`.
- @contezza/core/utils - `ContezzaObservables.forkJoin` ondersteunt ook (lege) objects.
- @contezza/dynamic-forms - Library opschonen.
- @contezza/dynamic-forms - Model `DynamicFormId` aangemaakt.
- @contezza/dynamic-forms - Fix sortering in veld `array`.
- @contezza/dynamic-forms - `ContezzaDynamicFormComponent` opschonen. Let op: model is hiermee aangepast.
- @contezza/dynamic-forms - Dialog model uitbreiden om `layoutId` en info popover te ondersteunen. Let op: model is hiermee aangepast.
- @contezza/dynamic-forms - Velden van type `array`, `dynamic` en `subform` worden geladen in `ContezzaDynamicFormModule`, dus ze hoeven niet apart geimporteerd te worden.
- @contezza/dynamic-forms - `ContezzaDynamicFormExtensionService` ondersteunt lazy loading van velden.

Interne changes:

- Dynamic Forms demo shell uitgebreid om dynamic-form dialogs te kunnen testen.

==== Release 2.1.0

Bugfixes/minor changes:

- @contezza/core/context - `FloatingButtonComponent` en `ToolbarComponent` aangemaakt.
- @contezza/core/context - `ActionsService` uitgebreid om actions te kunnen laden op basis van een array en niet alleen op basis van feature key.
- @contezza/dynamic-forms - Fix initialisatie van veld `info`.
- @contezza/dynamic-forms - Veld `array` ondersteunt `rules.readonly`.

==== Release 2.0.2

Bugfixes/minor changes:

- @contezza/dynamic-forms - Veld `dateRangeChip` zet waarden op null bij reset.


==== Release 2.0.1

Bugfixes/minor changes:

- @contezza/dynamic-forms - improvements


==== Release 2.0.0

Upgrades:

* ADF versie bijgewerkt met 6.0.0.
* ACA versie bijgewerkt met 4.0.0.


==== Release 1.1.0

Bugfixes/minor changes:

- @contezza/core/utils - Classes `BaseHttpClient` en `EncryptedHttpClient` aangemaakt.
- @contezza/core/utils - In class `ContezzaQueryParameters`: constructor argument type is aangepast; method `toString` negeert `null` waardes.
- @contezza/core/utils - `ContezzaObservables.from` voert de gegeven promise uit alleen bij subscriptie.
- @contezza/core/utils - Types `DistributiveKeyof` en `DistributiveOmit` aangemaakt. Type `Tree` hiermee refactored.

Let op: interface `ContezzaQueryParametersInterface` is verwijderd; input type van `ContezzaObservables.from` is gewijzigd.

==== Release 1.0.8

Bugfixes/minor changes:

- @contezza/core/utils - `ContezzaAdfUtils.makeRules` aangemaakt.

==== Release 1.0.7

Nieuwe features:

- @contezza/dynamic-forms - Veld `array` aangemaakt.

Bugfixes/minor changes:

- @contezza/core/utils - `ContezzaObservables.crossFilter` aangemaakt.
- @contezza/dynamic-forms - Velden `date` en `dateTime` zijn uitgebreid om eigenschappen `extras.min` en `extras.max` te ondersteunen https://support.contezza.nl/issues/24505[[#24505]].

==== Release 1.0.6

Nieuwe features:

- @contezza/dynamic-forms - Veld `multiautocomplete` is uitgebreid zodat suggesties extern (buiten de component zelf, bijvoorbeeld server-side) gefilterd kunnen worden.
- @contezza/dynamic-forms - Veld `radio-button` aangemaakt.

Bugfixes/minor changes:

- @contezza/core/utils - `ContezzaArrayUtils.sortBy` is case-insensitive.
- @contezza/core/utils - `ContezzaObservableOperators.dateToMoment` aangemaakt.
- @contezza/core/utils - `ContezzaQueryParametersInterface` accepteert keys met boolean waarde.
- @contezza/dynamic-forms - Popup van veld `dateRangeChip` sluit niet meer na een click binnen de popup https://support.contezza.nl/issues/24382[[#24382]].
- @contezza/dynamic-forms - Veld `dateTime` is uitgebreid om eigenschap `extras.min` te ondersteunen.
- @contezza/dynamic-forms - Interface `DynamicFormFieldSettings` is uitgebreid met eigenschap `hideRequiredMarker`. Deze wordt ondersteund door veld `input`.
- @contezza/dynamic-forms - Interface `ContezzaFormLayout` is uitgebreid met eigenschap `style`.
- @contezza/dynamic-forms - Validator `dynamic` aangemaakt.

Interne changes:

- Dynamic Forms demo shell aangemaakt in Demo App https://support.contezza.nl/issues/24435[[#24435]].
- Script `pack-libs` aangemaakt.

==== Release 1.0.5

Bugfixes/minor changes:

- @contezza/core/extensions: imports in extension bestanden ondersteunen nu ook primitive types.
- @contezza/core/utils: `ContezzaObservables.while` fixen en uitbreiden.
- @contezza/core/utils: `ContezzaObjectUtils.findKeys` ondersteunt nu parameter `allowNestedKeys`.

Let op: interfaces van `ContezzaObservables.while` en `ContezzaObjectUtils.findKeys` zijn hiermee aangepast en niet compatibel met de oude interfaces.

==== Release 1.0.4

Bugfixes/minor changes:

- @contezza/core/context: `ActionsService` uitbreiden, `featureKey` kan nu via input gegeven worden.
- @contezza/dynamicforms: fix stijl van button-toggle.
- @contezza/dynamicforms: date format kan via token geconfigureerd worden.
- @contezza/core/utils: operator `trackFacetBucketBy` sorteert nu de facets.
- @contezza/core/utils: class `BaseApi` en type `HttpMethod` toegevoegd.

==== Release 1.0.3

Bugfixes/minor changes:

- @contezza/dynamicforms return false waarde voor boolean
- @contezza/dynamicforms toevoegen validator isDirty

==== Release 1.0.2

Nieuwe features:

- @contezza/core/extensions: imports worden ondersteund in extension bestanden https://support.contezza.nl/issues/23966[[#23966]]

Bugfixes/minor changes:

- Algemeen: comments worden meegenomen en zijn beschikbaar als documentatie.
- @contezza/common: i18n uitbreiden.
- @contezza/core/extensions: bugfix.
- @contezza/core/utils: `map` operator uitbreiden om generieke callbacks te ondersteunen.

==== Release 1.0.1

Libraries uitbreiden.

==== Release 1.0.0

Libraries zijn beschikbaar op volgende eindpoints:

- @contezza/common
- @contezza/core/context
- @contezza/core/dialogs
- @contezza/core/directives
- @contezza/core/extensions
- @contezza/core/pipes
- @contezza/core/services
- @contezza/core/stores
- @contezza/core/utils
- @contezza/dynamic-forms
- @contezza/dynamic-forms/dialog
- @contezza/dynamic-forms/shared
- @contezza/js-console
- @contezza/js-console/shared
- @contezza/node-browser
- @contezza/node-browser/shared
- @contezza/people-group-picker
- @contezza/search/form
- @contezza/third-party/gridster
- @contezza/third-party/monaco
